### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by rykkqq** [Izumiko/iwaradl#1]
下载下来是exe的，双击打开没有用，用PyCharm 打开是乱码，有没有视频教程啊

**Comment by Izumiko** [comment]
这是一个命令行工具，需要你开一个cmd或者powershell，然后在里面输入命令来启动。这个工具是我自用的，就没写界面。另外，它是Go写的，要打开源代码的话，需要用GoLand或是vscode，PyCharm没法正确打开这个工程。

使用方法：
1. 编辑配置文件`config.yaml`,主要修改第一项下载保存的路径，还有第四项的代理服务器地址，一般看你的代理软件（v2rayn或是clash之类的）里面的设置。
2. 新建一个文本文件，比如叫`urllist.txt`，内容是你要下载的视频地址(https://www.iwara.tv/video/xxxxxxx 这种)，一行写一个。
3. 在cmd或者powershell里面运行`iwaradl -c config.yaml -l urllist.txt`，然后等下载完成。

**Comment by rykkqq** [comment]
是这样吗？
![屏幕截图 2024-03-30 195814](https://github.com/Izumiko/iwaradl/assets/164665536/e1658f03-42c2-4a10-ba75-8f078ab49f5f)

**Comment by Izumiko** [comment]
是的
![图片](https://github.com/Izumiko/iwaradl/assets/5195868/1c32ab63-feba-471c-9b9f-ab9bd23eaa01)

**Comment by rykkqq** [comment]
![image](https://github.com/Izumiko/iwaradl/assets/164665536/9be7164e-a98d-4e1c-8976-27bc8f2221e0)
我按完回车是这样的，文件夹里倒是多了个jobs.list

**Comment by Izumiko** [comment]
你代理服务器设置对了么

或者你可以用另一个项目去尝试下载：[dawn-lc/IwaraDownloadTool](https://github.com/dawn-lc/IwaraDownloadTool)

**Comment by rykkqq** [comment]
![image](https://github.com/Izumiko/iwaradl/assets/164665536/2baa5c42-021c-4437-a81a-0112a34da7bc)
我应该填哪个？

**Comment by Izumiko** [comment]
本地http的：`http://127.0.0.1:10809`
